"""The TechNest demo catalog: 12 gaming-accessory products with deliberate,
realistic affinity relationships baked into their definitions (compatibility
and frequently-bought-with hints). The actual support/confidence/lift
numbers are NOT hard-coded anywhere — they get computed in Phase 4 from the
transactions this affinity structure influences (see scripts/seed_demo.py).
"""

PRODUCTS = [
    {
        "key": "keyboard",
        "sku": "TN-KB-001",
        "name": "Nova Mechanical Keyboard",
        "description": "Hot-swappable mechanical keyboard with per-key RGB and tactile brown switches, built for long gaming and typing sessions.",
        "price_amount": 699,
        "category": "Keyboards",
        "stock_qty": 140,
        "specifications": {"switch_type": "Tactile Brown", "backlight": "Per-key RGB", "connectivity": "USB-C wired", "layout": "TKL"},
        "tags": ["mechanical", "rgb", "gaming", "hot-swappable"],
        "use_cases": ["gaming", "office", "streaming setup"],
        "compatibility": ["Windows", "macOS", "Linux"],
    },
    {
        "key": "mouse",
        "sku": "TN-MOUSE-001",
        "name": "Pro Wireless Gaming Mouse",
        "description": "Lightweight wireless gaming mouse with a 26,000 DPI optical sensor and 70-hour battery life.",
        "price_amount": 299,
        "category": "Mice",
        "stock_qty": 210,
        "specifications": {"dpi": "26000", "connectivity": "2.4GHz wireless + Bluetooth", "weight_g": "63", "battery_life_hours": "70"},
        "tags": ["wireless", "gaming", "lightweight"],
        "use_cases": ["gaming", "office"],
        "compatibility": ["Windows", "macOS", "Linux"],
    },
    {
        "key": "headset",
        "sku": "TN-HEADSET-001",
        "name": "Aero Gaming Headset",
        "description": "Over-ear gaming headset with 7.1 surround sound and a noise-cancelling detachable mic.",
        "price_amount": 599,
        "category": "Audio",
        "stock_qty": 95,
        "specifications": {"driver_size_mm": "50", "surround": "7.1 virtual", "mic": "Detachable, noise-cancelling", "connectivity": "USB / 3.5mm"},
        "tags": ["headset", "surround-sound", "streaming"],
        "use_cases": ["gaming", "streaming", "calls"],
        "compatibility": ["PC", "PS5", "Xbox", "Switch"],
    },
    {
        "key": "webcam",
        "sku": "TN-CAM-001",
        "name": "ClearView 1080p Webcam",
        "description": "1080p60 webcam with autofocus and a built-in privacy shutter, tuned for streaming and calls.",
        "price_amount": 399,
        "category": "Webcams",
        "stock_qty": 70,
        "specifications": {"resolution": "1080p60", "fov_degrees": "90", "autofocus": "Yes", "privacy_shutter": "Yes"},
        "tags": ["webcam", "streaming", "1080p"],
        "use_cases": ["streaming", "calls", "content creation"],
        "compatibility": ["Windows", "macOS", "OBS", "Zoom"],
    },
    {
        "key": "laptop_stand",
        "sku": "TN-STAND-001",
        "name": "Elevate Aluminum Laptop Stand",
        "description": "Adjustable aluminum laptop stand that improves airflow and posture at a desk.",
        "price_amount": 259,
        "category": "Desk Accessories",
        "stock_qty": 160,
        "specifications": {"material": "Aluminum", "adjustable_height": "Yes", "max_load_kg": "10", "foldable": "Yes"},
        "tags": ["laptop", "ergonomic", "desk setup"],
        "use_cases": ["office", "wfh", "productivity"],
        "compatibility": ["11-17 inch laptops"],
    },
    {
        "key": "usb_hub",
        "sku": "TN-HUB-001",
        "name": "Nexus 7-in-1 USB-C Hub",
        "description": "7-in-1 USB-C hub with HDMI 4K60, SD/microSD, and 100W passthrough charging.",
        "price_amount": 319,
        "category": "Desk Accessories",
        "stock_qty": 130,
        "specifications": {"ports": "HDMI, 2x USB-A, SD, microSD, USB-C PD", "hdmi_output": "4K@60Hz", "pd_charging_w": "100"},
        "tags": ["usb-c", "hub", "productivity"],
        "use_cases": ["office", "wfh", "travel"],
        "compatibility": ["USB-C laptops", "MacBook", "Windows laptops"],
    },
    {
        "key": "monitor_light",
        "sku": "TN-LIGHT-001",
        "name": "Halo Monitor Light Bar",
        "description": "Asymmetric screen light bar with adjustable warmth and brightness, glare-free on the display.",
        "price_amount": 359,
        "category": "Lighting",
        "stock_qty": 100,
        "specifications": {"mount": "Monitor clip-on", "color_temp_range_k": "2700-6500", "control": "Wired dial + remote"},
        "tags": ["lighting", "desk setup", "eye-comfort"],
        "use_cases": ["office", "streaming", "gaming"],
        "compatibility": ["Flat and curved monitors up to 27 inch"],
    },
    {
        "key": "desk_mat",
        "sku": "TN-MAT-001",
        "name": "Terrain XL Desk Mat",
        "description": "Extended stitched-edge desk mat with a smooth glide surface for mouse and keyboard.",
        "price_amount": 179,
        "category": "Desk Accessories",
        "stock_qty": 180,
        "specifications": {"size_cm": "90x40", "material": "Cloth top, rubber base", "edges": "Stitched"},
        "tags": ["desk-mat", "mousepad", "desk setup"],
        "use_cases": ["gaming", "office"],
        "compatibility": ["Standard desks"],
    },
    {
        "key": "controller",
        "sku": "TN-CTRL-001",
        "name": "Orbit Wireless Controller",
        "description": "Wireless controller with hall-effect thumbsticks and programmable back paddles.",
        "price_amount": 499,
        "category": "Controllers",
        "stock_qty": 85,
        "specifications": {"connectivity": "Bluetooth + 2.4GHz dongle", "battery_life_hours": "20", "paddles": "2 programmable"},
        "tags": ["controller", "wireless", "gaming"],
        "use_cases": ["console gaming", "pc gaming", "cloud gaming"],
        "compatibility": ["PC", "PS5", "Switch", "Android"],
    },
    {
        "key": "ssd",
        "sku": "TN-SSD-001",
        "name": "DriveX 1TB Portable SSD",
        "description": "Pocket-sized 1TB NVMe portable SSD with read speeds up to 1050MB/s.",
        "price_amount": 999,
        "category": "Storage",
        "stock_qty": 60,
        "specifications": {"capacity_gb": "1000", "interface": "USB 3.2 Gen 2", "read_speed_mbps": "1050", "write_speed_mbps": "1000"},
        "tags": ["storage", "ssd", "portable"],
        "use_cases": ["gaming", "content creation", "backup"],
        "compatibility": ["PC", "Mac", "PS5", "Xbox"],
    },
    {
        "key": "monitor",
        "sku": "TN-MON-001",
        "name": "Vantage 27\" 165Hz Gaming Monitor",
        "description": "27-inch QHD IPS gaming monitor with a 165Hz refresh rate and 1ms response time.",
        "price_amount": 3799,
        "category": "Monitors",
        "stock_qty": 35,
        "specifications": {"size_inch": "27", "resolution": "2560x1440", "refresh_rate_hz": "165", "panel": "IPS"},
        "tags": ["monitor", "gaming", "qhd", "high-refresh"],
        "use_cases": ["gaming", "content creation"],
        "compatibility": ["HDMI 2.0", "DisplayPort 1.4"],
    },
    {
        "key": "cooling_pad",
        "sku": "TN-COOL-001",
        "name": "Frost Laptop Cooling Pad",
        "description": "Dual-fan laptop cooling pad with quiet operation and adjustable stand angles.",
        "price_amount": 239,
        "category": "Desk Accessories",
        "stock_qty": 120,
        "specifications": {"fans": "2x 110mm", "noise_level_db": "< 24", "adjustable_angles": "5"},
        "tags": ["cooling", "laptop", "desk setup"],
        "use_cases": ["gaming", "wfh", "productivity"],
        "compatibility": ["12-17 inch laptops"],
    },
]

# (product_key, related_key, relation_type, base_affinity_weight)
# base_affinity_weight drives how often the two co-occur in generated orders —
# the actual support/confidence/lift are computed later from real transactions.
PRODUCT_RELATIONS = [
    ("keyboard", "mouse", "FREQUENTLY_BOUGHT_WITH", 0.55),
    ("mouse", "desk_mat", "FREQUENTLY_BOUGHT_WITH", 0.30),
    ("keyboard", "desk_mat", "RELATED", 0.18),
    ("headset", "webcam", "FREQUENTLY_BOUGHT_WITH", 0.28),
    ("headset", "monitor_light", "RELATED", 0.15),
    ("laptop_stand", "cooling_pad", "FREQUENTLY_BOUGHT_WITH", 0.40),
    ("laptop_stand", "usb_hub", "FREQUENTLY_BOUGHT_WITH", 0.32),
    ("ssd", "laptop_stand", "RELATED", 0.20),
    ("monitor", "monitor_light", "FREQUENTLY_BOUGHT_WITH", 0.35),
    ("monitor", "controller", "RELATED", 0.12),
    ("controller", "ssd", "RELATED", 0.10),
    ("usb_hub", "ssd", "COMPATIBLE", 0.22),
]
