"""unique constraint on payment provider_payment_link_id

Revision ID: 295f33c8efc3
Revises: 457327ed13f7
Create Date: 2026-08-25 09:15:36.628659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295f33c8efc3'
down_revision: Union[str, None] = '457327ed13f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payment_provider_payment_link_id', 'payments', ['provider_payment_link_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_provider_payment_link_id', 'payments', type_='unique')
    # ### end Alembic commands ###
