"""unique constraint on policy_rules and agent_permissions

Revision ID: 457327ed13f7
Revises: d851efe9c89d
Create Date: 2026-08-22 07:02:39.301137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457327ed13f7'
down_revision: Union[str, None] = 'd851efe9c89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_agent_permission_merchant_action', 'agent_permissions', ['merchant_id', 'action_code'])
    op.create_unique_constraint('uq_policy_rule_merchant_code', 'policy_rules', ['merchant_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_policy_rule_merchant_code', 'policy_rules', type_='unique')
    op.drop_constraint('uq_agent_permission_merchant_action', 'agent_permissions', type_='unique')
    # ### end Alembic commands ###
